sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install tox-travis
  - pip install codecov
  - pip install -r requirements.txt


script:
  - make lint
  - make test-all

after_success:
  - codecov --token=avm4PQNy8UecTz8q631p

deploy:
    provider: pypi
    user: pm3310
    password:
        secure: aVhUsOLjRT4cKI/duTPuj4oBK+kaC2AqhBBc9P6Rf4pt6chg+w5+/GtNWxd8hm2+6YrAJZxONFY+xRS46W8NhMeJWK9nvy/GitptjqMeeBaoyZIHvyGczTkzhdui4ExQe3CI9P4JFbUmIXueIfqT1gEDfkAt0toUGpWA9/8BgBAA4DcXRMpqQT8M35sxf6cnBppdO8KYbA05rGQWjK+AEA2p0PtwtrChemECdVdrFlxl5qFb99ppLQ/6yuo1mLSfZzzVUIhgFP8ntEx59GoI4gxBHLabBAdrPUHxg9f9kCA2WUl+bgSs1uS0YF5HKWIZleFlg7YtuHm2dPKNVjHjT/sc9gjcDPa2eowPFWaa/5IvJMxcxTb5IzPocZugVcHil5oyq4wAGeoXQSj1gSJahBBmrGXvq8cFuCf0AOxvq3ZQyg2+EPqkD2ci9KuxNYEYMeLTCkvhUBaqa2gpI5XiyUbb7etcDikEaO1iNqVkyzOf7gz3oXLbOcCVztBlpPFN2hnWWAavhw6P1PbXxS0Nvfm64EWKfCNVIU22UgoMMlZzHqroGEGkHc9sV6oLUYCjimp8imVwAq/VMFu75oYa54kFWC1o1BHHbaqR4/yJlgmc+4XwfIRZe8jExlTydYTTM8VJ2ZWjUzMAcvaDD5FJx7faSo2nDX6kSF27gDBJahY=
    on:
        tags: true
        branch: master
